erDiagram
    PERSON {
        string id PK "XSD:ID"
        string name "Regex: \w+ \w+"
        string gender "M|F|other"
        int children_count "Required"
        int siblings_count "Required"
    }

    PERSON ||--o| PERSON : "spouse (0..1)"

    
    PERSON ||--o{ PARENT_CHILD_LINK : "as_parent"
    PERSON ||--o{ PARENT_CHILD_LINK : "as_child"
    PARENT_CHILD_LINK {
        string parent_id FK "-> PERSON.id"
        string child_id FK "-> PERSON.id"
    }

    PERSON ||--o{ SIBLING_LINK : "person_ref"
    PERSON ||--o{ SIBLING_LINK : "sibling_ref"
    SIBLING_LINK {
        string person_id FK "-> PERSON.id"
        string sibling_id FK "-> PERSON.id"
    }
